name: Test and Build

on:
  push:
    branches: [ main, develop, 'feature/*' ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-and-build:
    name: Test and Build
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [22.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: fitness-tracker-app/package-lock.json
    
    - name: Install dependencies
      working-directory: ./fitness-tracker-app
      run: npm ci
    
    - name: Run tests
      working-directory: ./fitness-tracker-app
      run: npm test -- --coverage --watchAll=false
      
    - name: Build application
      working-directory: ./fitness-tracker-app
      run: npm run build
      
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-files
        path: fitness-tracker-app/build
        
    - name: Archive test coverage
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: fitness-tracker-app/coverage